# Generated by Django 2.0.12 on 2020-04-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grancum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='գրանցում',
            name='ԳրանցմանԱմսաթիվ',
            field=models.DateField(auto_now=True, null=True, default = '2019-10-10'),
        ),
        migrations.AddField(
            model_name='գրանցում',
            name='Հայրանուն',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Հայրանուն'),
        ),
    ]
