# Generated by Django 2.0.12 on 2020-04-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grancum', '0003_auto_20200405_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='գրանցում',
            name='Ազգանուն',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Ազգանուն'),
        ),
        migrations.AlterField(
            model_name='գրանցում',
            name='Անուն',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='գրանցում',
            name='ԳրանցմանԱմսաթիվ',
            field=models.DateField(auto_now=True, null=True, default = '2019-10-10'),
        ),
        migrations.AlterField(
            model_name='գրանցում',
            name='Հայրանուն',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Հայրանուն'),
        ),
    ]
