# Generated by Django 2.0.12 on 2020-04-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grancum', '0004_auto_20200405_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='գրանցում',
            name='ԳրանցմանԱմսաթիվ',
            field=models.DateField(auto_now=True, null=True, default = '2019-10-10'),
        ),
    ]
