# Generated by Django 2.0.12 on 2020-04-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grancum', '0005_auto_20200409_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='գրանցում',
            name='ԳրանցմանԱմսաթիվ',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
