# Generated by Django 2.0.12 on 2020-04-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grancum', '0006_auto_20200409_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='գրանցում',
            name='Ազգանուն',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Ազգանուն'),
        ),
    ]
