# Generated by Django 2.0.12 on 2020-04-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Grancum', '0008_auto_20200409_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Բուժկանխարգելիչ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ՕՕՕրրր', models.IntegerField()),
                ('ԱԱԱմիսսս', models.IntegerField()),
                ('ՏՏՏարիիի', models.IntegerField()),
                ('Նշանակված', models.CharField(max_length=10000)),
                ('Բուժկանխարգելիչմ', models.CharField(max_length=10000)),
                ('Զորամաս', models.CharField(max_length=10000)),
                ('jo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grancum.Գրանցում')),
            ],
        ),
    ]
