# Generated by Django 2.0.12 on 2020-04-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anamnez', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='անամնեզ',
            old_name='հհ',
            new_name='ՀՀ',
        ),
    ]
