# Generated by Django 2.0.12 on 2020-04-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anamnez', '0002_auto_20200409_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='անամնեզ',
            name='ՀՀ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Grancum.Գրանցում', unique=True),
        ),
    ]
