# Generated by Django 2.0.12 on 2020-04-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yndhanurtexekutyunner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ընդհանուրտեղեկություններ',
            name='ԸնտանեկանԴրությունը',
            field=models.TextField(blank=True, help_text='ամուրի, ամուսնացած, երեխաների և խնամակյալների թիվը', max_length=1000, null=True, verbose_name='Ընտանեկան դրություն'),
        ),
        migrations.AlterField(
            model_name='ընդհանուրտեղեկություններ',
            name='Կրթությունը',
            field=models.CharField(blank=True, help_text='ընդհանուր, զինվորական, հատուկ մասնագիտական', max_length=1000, null=True, verbose_name='Կրթությունը'),
        ),
    ]
