# Generated by Django 2.0.12 on 2020-04-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grancum', '0002_auto_20200403_1644'),
        ('yndhanurtexekutyunner', '0002_auto_20200404_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='ընդհանուրտեղեկություններ',
            name='հհ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Grancum.Գրանցում'),
        ),
    ]
