# Generated by Django 2.0.12 on 2020-04-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yndhanurtexekutyunner', '0004_auto_20200404_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ընդհանուրտեղեկություններ',
            name='ԾառայությանԱնցնելուԱմսաթիվը',
            field=models.DateField(blank=True, null=True, verbose_name='Ծառայության անցնելու ամսաթիվը', default = '2019-10-10'),
        ),
        migrations.AlterField(
            model_name='ընդհանուրտեղեկություններ',
            name='ԾննդյանՏարեթիվը',
            field=models.DateField(blank=True, null=True, verbose_name='Ծննդյան տարեթիվը', default = '2019-10-10'),
        ),
    ]
