# Generated by Django 2.0.12 on 2020-04-13 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Grancum', '0008_auto_20200409_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='ՄյուսՄասնագետներ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Տարրի', models.IntegerField()),
                ('Ամիիս', models.IntegerField()),
                ('Օօր', models.IntegerField()),
                ('Մյուս', models.TextField(max_length=10000)),
                ('pa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grancum.Գրանցում')),
            ],
        ),
    ]
