# Generated by Django 2.0.12 on 2020-04-13 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Grancum', '0008_auto_20200409_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Առողջական',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('տարրիիի', models.IntegerField()),
                ('ամիիսսս', models.IntegerField()),
                ('օօրրր', models.IntegerField()),
                ('Ախտորոշու', models.CharField(max_length=10000)),
                ('ԱԱռողջական', models.CharField(max_length=10000)),
                ('Հաշվառվել', models.CharField(max_length=10000)),
                ('Ֆիզպատ', models.CharField(max_length=10000)),
                ('tt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grancum.Գրանցում')),
            ],
        ),
    ]
