# Generated by Django 2.0.12 on 2020-04-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grancum', '0008_auto_20200409_1514'),
        ('Gangatner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='գանգաթներ',
            name='gg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Grancum.Գրանցում'),
            preserve_default=False,
        ),
    ]
