# Generated by Django 2.0.12 on 2020-04-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carayutyun', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ծառայություն',
            old_name='հհ',
            new_name='ll',
        ),
    ]
