# Generated by Django 2.0.12 on 2020-04-10 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Grancum', '0008_auto_20200409_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ֆիզիկական',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Տարիի', models.IntegerField()),
                ('Ամիսս', models.IntegerField()),
                ('Օրր', models.IntegerField()),
                ('Քաշը', models.IntegerField()),
                ('Հասակը', models.IntegerField()),
                ('ԿրծքավանդակՀանգիստ', models.CharField(max_length=100)),
                ('ԿրծքավանդակՇնչելիս', models.CharField(max_length=100)),
                ('ԿրծքավանդակԱրտաշնչելիս', models.CharField(max_length=100)),
                ('ՓորիՇրջագիծը', models.IntegerField()),
                ('Շնչաչափը', models.IntegerField()),
                ('Աջ', models.IntegerField()),
                ('Ձախ', models.IntegerField()),
                ('oo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grancum.Գրանցում')),
            ],
        ),
    ]
